### ISSUE TITLE
Incorrect releases for 5.0.5 and 5.1.1

### ISSUE THREAD

**Issue by johnbillion** [wp-phpunit/issues#2]
Thanks for this repo, it's just what's needed :-)

I've noticed two problems:

1. There's [a `5.0.5` release tagged](https://github.com/wp-phpunit/wp-phpunit/releases/tag/5.0.5), but no such version of WordPress exists. The latest in the 5.0.x branch is 5.0.4. Ref: https://wordpress.org/download/releases/
2. The [`5.1.1` release](https://github.com/wp-phpunit/wp-phpunit/releases/tag/5.1.1) was tagged 21 days ago, but WordPress 5.1.1 was only released two days ago.

**Comment by aaemnnosttv** [comment]
Thanks John 😄 

1. It's coming from this tag https://github.com/WordPress/wordpress-develop/releases/tag/5.0.5
1. 5.1.1 shares the same commit as 5.1.0 (https://github.com/wp-phpunit/wp-phpunit/commit/b3948a3df9507af4d2367c4fa1ba3bac34a35961) since there was no change in the subset of files between those releases which is why the date is older than the actual date it was tagged.

**Comment by johnbillion** [comment]
Thanks x2!

I'll check with Pento to see what's up with 5.0.5.
