### ISSUE TITLE
5.1.1 and 5.0.4 not appearing in Packagist

### ISSUE THREAD

**Issue by johnbillion** [wp-phpunit/issues#3]
Possibly related to #2, the latest version in the 5.0.x and 5.1.x branches aren't present on Packagist. https://packagist.org/packages/wp-phpunit/wp-phpunit

**Comment by aaemnnosttv** [comment]
Thanks John. I've gone ahead and triggered an update manually and they're all there now.
Could be there was an issue with the webhook delivery on the last build. I'll take a look. Thanks for letting me know!

**Comment by aaemnnosttv** [comment]
Just to follow up here, there was a flaw in the configuration of the webhook for packagist. It was configured to send "Just the `push` event" (which I believe is the default), however this will only be triggered if new commits are pushed. In this case, only new tags were being added since the codebase had not changed since the last tag.

I've updated the webhook to be triggered on branch/tag creation now as well, so Packagist should  still get notified about the update even if no new commits are pushed 👍
